# Generated by Django 5.0.3 on 2024-04-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_image.jpg', upload_to='uploads/images')),
                ('name', models.CharField(default='Name', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=10.0, max_digits=6)),
                ('category', models.CharField(default='category', max_length=100)),
            ],
        ),
    ]
